### PR TITLE
Fix wrong file captured

### PR DESCRIPTION
**Pull request by dityaaa**
<details>
    <summary>PHPUnit output</summary>

   Using --teamcity flag

   ```
      ##teamcity[testFailed name='test_users_can_authenticate_using_the_login_screen' message='The user is authenticated|nFailed asserting that true is false.' details=' {{ GITHUB_WORKSPACE }}/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithAuthentication.php:62|n {{ GITHUB_WORKSPACE }}/tests/Feature/AuthenticationTest.php:30|n ' duration='207' flowId='2873']

      ##teamcity[testFailed name='test_users_can_not_authenticate_with_invalid_password' message='The user is not authenticated|nFailed asserting that false is true.' details=' {{ GITHUB_WORKSPACE }}/tests/Feature/AuthenticationTest.php:43|n ' duration='113' flowId='2873']
   ```

</details>

Current pattern is only capture first file (usually in vendor folder), thus making it not displayed on pull request (because vendor folder is usually not uploaded). This changes make the pattern capture the last file (real test file), while still capture first file if it didn't contain multiple files. 

Current pattern (tested using [https://problem-matcher.netlify.app/](https://problem-matcher.netlify.app/))

```json
[
    {
        "file": "vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithAuthentication.php",
        "line": "62",
        "message": "The user is authenticated|nFailed asserting that true is false."
    },
    {
        "file": "tests/Feature/AuthenticationTest.php",
        "line": "43",
        "message": "The user is not authenticated|nFailed asserting that false is true."
    }
]
```

Using updated pattern

```json
[
    {
        "file": "tests/Feature/AuthenticationTest.php",
        "line": "30",
        "message": "The user is authenticated|nFailed asserting that true is false."
    },
    {
        "file": "tests/Feature/AuthenticationTest.php",
        "line": "43",
        "message": "The user is not authenticated|nFailed asserting that false is true."
    }
]
```

### CODE REVIEW

**Comment by mheap** [comment]
@dityaaa This managed to slip through the cracks, sorry for the delay!

Why did the `GITHUB_WORKSPACE` path need escaping?

**Comment by dityaaa** [comment]
Long story short, I use regex101 to test the regex, then it complain about unescaped delimiter. That is why I escape the `GITHUB_WORKSPACE`. But I believe it can work without escaping the `GITHUB_WORKSPACE`. 
Do you want me to remove that escape?

**Comment by mheap** [comment]
@dityaaa Yes please. I can see how the updated regex works, but the updated replace seemed out of place.

Once that's done I'll test and merge 🙌

**Comment by dityaaa** [comment]
@mheap I just tested the new commit in my project, and it worked. Maybe you want to test it a little bit more before merge

**Comment by ghost** [comment]
@mheap Can this be merged? I would really like to use this action but without this fix it is not working properly.

**Comment by mheap** [comment]
@dityaaa I _finally_ got around to writing some unit tests for this and shipping the fix (thanks for the prod @PrinsFrankTemper)

Thank you so much for the contribution and your patience. You should be able to use this action going forwards for your tests

**Pull request merged**
